[package]
name = "combies"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raylib = { version = "3.7" }
structopt = "0.3.26"
toml = "0.5.9"
rand = "0.8.5"